### ISSUE TITLE
About Training Dataset

### ISSUE THREAD

**Issue by jwfanDL** [YuYue525/MobileSAM-pytorch#15]
Amazing work. Thank you for providing codes!

I have a question about training dataset. I notice that in you train.py it seems that you utilize training data from sa_000000 to sa_000019 (2% of SA-1B). Your reproduced results are based on this setting or as written in README.md (1% of SA-1B)

**Comment by YuYue525** [comment]
In MobileSAM paper, it claimed that they use 1% SA-1B. If you wish, you can use any size dataset your hardware allows. Actually, the model weights I provided is trained on 8% SA-1B.

**Comment by jwfanDL** [comment]
Thank you for you reply!

I have deployed experiment based on the setting that use 1% SA-1B. Have you reproduce the results based on the setting in original paper? If not, I'd like to carefully check training settings that can contribute to your project.

**Comment by YuYue525** [comment]
We tried 1% SA-1B, but the performance is slightly worse than the weights provided by the official MobileSAM team. You can try.

**Comment by jwfanDL** [comment]
If I find any settings or tricks that can boost the performance, I'll contact you by raising a new issue.
